<?php
$title = 'List of articles';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<!--<div class="hero-unit">-->
<!--    <h1>--><?php //echo sprintf($this->translate('%sВелика вітчизняна війна%s'), '<span class="zf-green">', '</span>') ?><!--</h1>-->
<!--</div>-->

<p>
    <!--    <a href="--><?php //echo $this->url('articles', array('action'=>'add'));?><!--">Add new album</a>-->
</p>

<?php //var_dump($articles); ?>

<table class="table">
    <tr>
        <th>Title</th>
        <th>Content</th>
        <th>Date</th>
        <th>Created by</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($articles as $album) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($album->title);?></td>
        <td><?php echo $this->escapeHtml($album->content);?></td>
        <td><?php echo $this->escapeHtml($album->date);?></td>
        <td><?php echo $this->escapeHtml($album->created_by);?></td>
        <td><?php echo $this->escapeHtml($album->id);?></td>
        <td>
<!--            <a href="--><?php //echo $this->url('Swar', array('action'=>'edit', 'id' => $album->id));?><!--">Edit</a>-->
<!--            <a href="--><?php //echo $this->url('Swar', array('action'=>'delete', 'id' => $album->id));?><!--">Delete</a>-->
        </td>
    </tr>
    <?php endforeach; ?>
</table>